"use client";

import "../components-premium.css";

import { useState } from "react";
import { AlertTriangle, Bell, Check, ChevronDown, CircleHelp, Copy, Database, Download, Inbox, LoaderCircle, MoreHorizontal, Plus, Search, Sparkles, UploadCloud, UserRound, X } from "lucide-react";
import { LoraniqShell } from "@/components/loraniq-shell";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Progress } from "@/components/ui/progress";

const statusItems=[{label:"موفق",tone:"success"},{label:"در انتظار",tone:"warning"},{label:"ناموفق",tone:"danger"},{label:"اطلاعات",tone:"info"},{label:"خنثی",tone:"neutral"}];
const people=["سارا یوسفی","آرمان زمانی","نگار قاسمی","پارسا راد"];
export default function ComponentsPage(){
 const[loading,setLoading]=useState(false);const[state,setState]=useState<"data"|"empty"|"error">("data");const[checked,setChecked]=useState(true);const[toast,setToast]=useState("");
 const notify=(text:string)=>{setToast(text);window.setTimeout(()=>setToast(""),1900)};
 const fakeLoad=()=>{setLoading(true);window.setTimeout(()=>setLoading(false),900)};
 return <LoraniqShell active="components"><main id="main-content" className="main-content components-page">
  <section className="components-hero"><div><span className="components-kicker"><Sparkles/> Loraniq UI Lab</span><h1>یک زبان بصری منسجم؛ از دکمه و فرم تا empty/error/loading.</h1><p>این صفحه stateهای پایه و الگوهای تعاملی را کنار هم قرار می‌دهد تا توسعه‌دهنده قبل از ساخت صفحه جدید، رفتار و ظاهر استاندارد را ببیند.</p><div className="components-meta"><span>Semantic color</span><span>RTL/LTR</span><span>Dark ready</span><span>Keyboard focus</span><span>Reduced motion</span></div></div><div className="components-hero-card"><div><b>Component coverage</b><strong>Core UI states</strong><span>Actions · Form · Status · Feedback · Data</span></div><Progress value={86}/><footer><span>پوشش فعلی سیستم پایه</span><b>۸۶٪</b></footer></div></section>
  <section className="component-grid two">
   <article className="component-card"><header><div><span>Actions</span><h2>دکمه‌ها و اکشن‌ها</h2></div><MoreHorizontal/></header><div className="button-showcase"><Button onClick={()=>notify("اکشن اصلی اجرا شد")}><Plus/> اکشن اصلی</Button><Button variant="outline"><Download/> دانلود</Button><Button variant="secondary"><Copy/> کپی</Button><Button variant="ghost"><CircleHelp/> راهنما</Button><Button disabled>غیرفعال</Button><Button onClick={fakeLoad} disabled={loading}>{loading?<LoaderCircle className="spin"/>:<UploadCloud/>}{loading?"در حال پردازش...":"پردازش"}</Button></div><div className="icon-actions"><button aria-label="جستجو"><Search/></button><button aria-label="اعلان"><Bell/><i/></button><button aria-label="افزودن"><Plus/></button><button aria-label="بستن"><X/></button></div></article>
   <article className="component-card"><header><div><span>Semantic states</span><h2>وضعیت‌ها و Badgeها</h2></div><Database/></header><div className="status-grid">{statusItems.map((item)=><span key={item.label} className={`status-pill ${item.tone}`}><i/>{item.label}</span>)}</div><div className="progress-list"><div><span>Onboarding</span><b>۷۸٪</b><Progress value={78}/></div><div><span>Storage</span><b>۵۶٪</b><Progress value={56}/></div><div><span>هدف فروش</span><b>۹۱٪</b><Progress value={91}/></div></div></article>
  </section>
  <section className="component-grid three">
   <article className="component-card"><header><div><span>Fields</span><h2>فرم و ورودی</h2></div></header><div className="field-stack"><label><b>نام پروژه</b><Input defaultValue="Loraniq Admin"/></label><label><b>جستجو</b><span className="component-input-icon"><Search/><Input placeholder="جستجو در داده‌ها..."/></span></label><label><b>وضعیت</b><span className="component-select"><select defaultValue="active"><option value="active">فعال</option><option value="paused">متوقف</option><option value="done">تکمیل</option></select><ChevronDown/></span></label><label><b>توضیحات</b><textarea placeholder="یادداشت کوتاه..."/></label></div></article>
   <article className="component-card"><header><div><span>Selection</span><h2>انتخاب و کنترل</h2></div></header><div className="control-stack"><button className="check-row" onClick={()=>setChecked((value)=>!value)} aria-pressed={checked}><span className={checked?"checked":""}>{checked&&<Check/>}</span><div><b>اعلان‌های مهم</b><small>رویدادهای مهم محصول را نشان بده</small></div></button><label className="radio-row-mini"><input type="radio" name="plan" defaultChecked/><span/><div><b>حرفه‌ای</b><small>برای تیم‌های محصول</small></div></label><label className="radio-row-mini"><input type="radio" name="plan"/><span/><div><b>ساده</b><small>برای استفاده سبک</small></div></label><label className="range-row"><b>شدت اعلان</b><input type="range" defaultValue="62"/></label></div></article>
   <article className="component-card"><header><div><span>People</span><h2>Avatar و Team</h2></div><UserRound/></header><div className="people-list">{people.map((name,index)=><div key={name}><span className={`person-avatar avatar-${index}`}>{name.slice(0,1)}</span><div><b>{name}</b><small>{index%2?"Product Designer":"Frontend Engineer"}</small></div><span className={index===2?"away":"online"}/></div>)}</div><Button variant="outline" className="team-button"><Plus/> دعوت عضو جدید</Button></article>
  </section>
  <section className="component-card states-card"><header><div><span>Async & feedback</span><h2>Loading، Empty و Error state</h2></div><div className="state-switcher"><button className={state==="data"?"active":""} onClick={()=>setState("data")}>Data</button><button className={state==="empty"?"active":""} onClick={()=>setState("empty")}>Empty</button><button className={state==="error"?"active":""} onClick={()=>setState("error")}>Error</button></div></header>{state==="data"?<div className="mini-table"><div className="mini-table-head"><span>کاربر</span><span>نقش</span><span>وضعیت</span><span>آخرین فعالیت</span></div>{people.slice(0,3).map((name,index)=><div key={name}><span><i className={`person-avatar avatar-${index}`}>{name.slice(0,1)}</i><b>{name}</b></span><span>{index?"Designer":"Engineer"}</span><span><em className="status-pill success"><i/>فعال</em></span><span>{index+2} دقیقه پیش</span></div>)}</div>:state==="empty"?<div className="component-state"><Inbox/><h3>هنوز داده‌ای ثبت نشده</h3><p>اولین مورد را اضافه کن تا این بخش فعال شود.</p><Button><Plus/> افزودن مورد</Button></div>:<div className="component-state error"><AlertTriangle/><h3>دریافت داده ناموفق بود</h3><p>ارتباط برقرار نشد. دوباره تلاش کن یا تنظیمات شبکه را بررسی کن.</p><Button variant="outline" onClick={()=>setState("data")}>تلاش دوباره</Button></div>}</section>
  <section className="component-grid two"><article className="component-card"><header><div><span>Skeleton</span><h2>Loading composition</h2></div></header><div className="skeleton-demo"><div className="skeleton-avatar"/><div><span/><span/><span/></div></div><div className="skeleton-bars"><span/><span/><span/><span/></div></article><article className="component-card"><header><div><span>Motion</span><h2>Motion tokens</h2></div></header><div className="motion-demo"><span className="motion-dot fast">Fast</span><span className="motion-dot base">Base</span><span className="motion-dot slow">Slow</span></div><p className="motion-note">حرکت‌ها باید هدفمند، کوتاه و قابل حذف با Reduced Motion باشند؛ animation نمایشی بی‌دلیل وارد محصول نمی‌شود.</p></article></section>
  {toast&&<div className="component-toast" role="status"><Check/>{toast}</div>}
 </main></LoraniqShell>
}
