"use client";

import { useMemo, useState } from "react";
import { Check, CheckCircle2, ChevronDown, MoreHorizontal, Plus, Search, ShieldCheck, Sparkles, UserPlus, UsersRound, X } from "lucide-react";
import { LoraniqShell } from "@/components/loraniq-shell";
import { Button } from "@/components/ui/button";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";

const seed=[
{id:1,name:"حسن مجتهدی",email:"hassan@loraniq.dev",role:"Owner",team:"Product",status:"فعال",last:"همین حالا"},
{id:2,name:"سارا یوسفی",email:"sara@loraniq.dev",role:"Admin",team:"Design",status:"فعال",last:"۴ دقیقه پیش"},
{id:3,name:"آرمان زمانی",email:"arman@loraniq.dev",role:"Developer",team:"Engineering",status:"فعال",last:"۱۸ دقیقه پیش"},
{id:4,name:"نگار قاسمی",email:"negar@loraniq.dev",role:"QA",team:"Quality",status:"فعال",last:"۱ ساعت پیش"},
{id:5,name:"پارسا راد",email:"parsa@loraniq.dev",role:"Finance",team:"Finance",status:"دعوت‌شده",last:"—"},
{id:6,name:"آوا کریمی",email:"ava@loraniq.dev",role:"Viewer",team:"Marketing",status:"غیرفعال",last:"۱۲ روز پیش"},
];
export default function UsersPage(){
 const[users,setUsers]=useState(seed);const[query,setQuery]=useState("");const[role,setRole]=useState("همه");const[selected,setSelected]=useState<number[]>([]);const[invite,setInvite]=useState(false);const[invited,setInvited]=useState(false);
 const visible=useMemo(()=>users.filter((user)=>(role==="همه"||user.role===role)&&`${user.name} ${user.email} ${user.team}`.toLowerCase().includes(query.toLowerCase())),[users,query,role]);
 const toggle=(id:number)=>setSelected((items)=>items.includes(id)?items.filter((item)=>item!==id):[...items,id]);
 const inviteUser=()=>{setInvite(false);setInvited(true);window.setTimeout(()=>setInvited(false),2200)};
 return <LoraniqShell active="users"><main id="main-content" className="main-content users-page">
  <section className="users-hero" aria-labelledby="page-title"><div><span className="users-kicker"><ShieldCheck/> Identity & access</span><h1 id="page-title">کاربر، نقش و دسترسی را بدون ابهام مدیریت کن.</h1><p>جستجو، role filter، انتخاب چندتایی، دعوت کاربر و status management در یک صفحه responsive و آماده توسعه permissionهای واقعی.</p><div className="users-actions"><Button onClick={()=>setInvite(true)}><UserPlus/> دعوت کاربر</Button><Button variant="outline"><ShieldCheck/> نقش‌ها و دسترسی‌ها</Button></div></div><div className="users-summary"><div><span>کاربران فعال</span><strong>{users.filter((u)=>u.status==="فعال").length.toLocaleString("fa-IR")}</strong><small>از {users.length.toLocaleString("fa-IR")} حساب</small></div><div><span>Admin / Owner</span><strong>{users.filter((u)=>["Admin","Owner"].includes(u.role)).length.toLocaleString("fa-IR")}</strong><small>دسترسی سطح بالا</small></div></div></section>
  {invited&&<div className="users-success"><CheckCircle2/><span>دعوت‌نامه کاربر با موفقیت آماده ارسال شد.</span></div>}
  <section className="users-panel"><div className="users-toolbar"><div className="users-search"><Search/><input aria-label="جستجوی کاربران" value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="نام، ایمیل یا تیم..."/></div><label className="users-role"><span>نقش</span><select aria-label="فیلتر نقش" value={role} onChange={(e)=>setRole(e.target.value)}><option>همه</option>{["Owner","Admin","Developer","QA","Finance","Viewer"].map((item)=><option key={item}>{item}</option>)}</select><ChevronDown/></label></div>
   {selected.length>0&&<div className="users-bulk"><b>{selected.length.toLocaleString("fa-IR")} کاربر انتخاب شده</b><div><button onClick={()=>setUsers((items)=>items.map((u)=>selected.includes(u.id)?{...u,status:"فعال"}:u))}>فعال‌سازی</button><button onClick={()=>setSelected([])}>لغو انتخاب</button></div></div>}
   <div className="users-table-head"><span>انتخاب</span><span>کاربر</span><span>نقش</span><span>تیم</span><span>وضعیت</span><span>آخرین فعالیت</span><span/></div><div className="users-rows">{visible.map((user)=><article key={user.id} className={selected.includes(user.id)?"selected":""}><button className="user-check" aria-label={`انتخاب ${user.name}`} onClick={()=>toggle(user.id)}><span>{selected.includes(user.id)&&<Check/>}</span></button><div className="user-identity"><span className={`user-avatar avatar-${(user.id-1)%4}`}>{user.name.slice(0,1)}</span><div><b>{user.name}</b><small>{user.email}</small></div></div><span className="user-role-pill">{user.role}</span><span>{user.team}</span><span className={`user-status ${user.status==="فعال"?"active":user.status==="دعوت‌شده"?"invited":"inactive"}`}><i/>{user.status}</span><span className="user-last">{user.last}</span><DropdownMenu><DropdownMenuTrigger asChild><button className="user-menu" aria-label={`عملیات ${user.name}`}><MoreHorizontal/></button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem>ویرایش کاربر</DropdownMenuItem><DropdownMenuItem onClick={()=>setUsers((items)=>items.map((u)=>u.id===user.id?{...u,status:u.status==="فعال"?"غیرفعال":"فعال"}:u))}>تغییر وضعیت</DropdownMenuItem><DropdownMenuItem>بازنشانی دسترسی</DropdownMenuItem></DropdownMenuContent></DropdownMenu></article>)}</div>{!visible.length&&<div className="users-empty"><UsersRound/><h2>کاربری پیدا نشد</h2><p>جستجو یا فیلتر نقش را تغییر دهید.</p></div>}</section>
  {invite&&<div className="users-modal" role="dialog" aria-modal="true" aria-label="دعوت کاربر"><div className="users-modal-card"><header><div><span><Sparkles/></span><div><h2>دعوت عضو جدید</h2><p>اطلاعات اولیه و سطح دسترسی را مشخص کنید.</p></div><button onClick={()=>setInvite(false)} aria-label="بستن"><X/></button></header><div className="invite-fields"><label><b>ایمیل</b><input defaultValue="new.member@example.com"/></label><label><b>نقش</b><select defaultValue="Developer"><option>Developer</option><option>Admin</option><option>Viewer</option><option>QA</option></select></label><label><b>تیم</b><input defaultValue="Engineering"/></label></div><footer><Button variant="outline" onClick={()=>setInvite(false)}>انصراف</Button><Button onClick={inviteUser}><Plus/> ارسال دعوت</Button></footer></div></div>}
 </main></LoraniqShell>
}
