"use client";

import { useMemo, useState } from "react";
import { ArrowUpRight, CalendarDays, CheckCircle2, ChevronDown, CircleAlert, FolderKanban, MoreHorizontal, Plus, Search, UsersRound } from "lucide-react";
import { LoraniqShell } from "@/components/loraniq-shell";
import { Button } from "@/components/ui/button";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";

const projects=[
{id:1,name:"Loraniq Commerce",client:"Northstar",progress:78,health:92,status:"در حال اجرا",deadline:"۲۸ مهر",budget:"۴۸۰ م",members:["ح","م","س"]},
{id:2,name:"Atlas Mobile",client:"Atlas",progress:61,health:84,status:"در حال اجرا",deadline:"۵ آبان",budget:"۳۲۰ م",members:["ن","آ","ر"]},
{id:3,name:"Vista Brand OS",client:"Vista Studio",progress:93,health:96,status:"بازبینی",deadline:"۲۲ مهر",budget:"۲۶۰ م",members:["د","ک"]},
{id:4,name:"Dorsa Intelligence",client:"Dorsa",progress:42,health:71,status:"ریسک",deadline:"۱۲ آبان",budget:"۵۹۰ م",members:["پ","م","ع"]},
{id:5,name:"Lumen Finance",client:"Lumen",progress:100,health:98,status:"تکمیل‌شده",deadline:"۱۵ مهر",budget:"۲۱۰ م",members:["س","ف"]},
{id:6,name:"Hexa Support",client:"Hexa",progress:34,health:77,status:"در حال اجرا",deadline:"۱۸ آبان",budget:"۱۸۰ م",members:["ه","ی","ر"]},
];
const tasks={todo:["نهایی‌کردن Scope نسخه موبایل","تعریف Event taxonomy","مرور API قراردادها"],doing:["بازطراحی Checkout","تست migration داده","Dashboard analytics"],review:["Notification center","Dark mode tokens"],done:["Project kickoff","Design system baseline","Auth flow"]};

export default function ProjectsPage(){
 const [filter,setFilter]=useState("همه");const [query,setQuery]=useState("");const [created,setCreated]=useState(false);
 const visible=useMemo(()=>projects.filter((p)=>(filter==="همه"||p.status===filter)&&(`${p.name} ${p.client}`.toLowerCase().includes(query.toLowerCase()))),[filter,query]);
 return <LoraniqShell active="projects"><main id="main-content" className="main-content projects-page">
  <section className="projects-hero" aria-labelledby="page-title"><div><span className="projects-kicker"><FolderKanban/> Project command</span><h1 id="page-title">پروژه‌ها را از سطح سلامت تا آخرین Task کنترل کن.</h1><p>Portfolio، ریسک، پیشرفت، بودجه، تیم و Board در یک فضای کاری منسجم؛ برای مدیر پروژه‌ای که باید سریع تصمیم بگیرد.</p><div className="projects-actions"><Button onClick={()=>setCreated(true)}><Plus/> پروژه جدید</Button><Button variant="outline"><CalendarDays/> برنامه زمان‌بندی</Button></div></div><div className="projects-pulse"><span>Portfolio health</span><strong>۸۷</strong><em><ArrowUpRight/> +۶ امتیاز</em><div><i style={{width:"87%"}}/></div><small>۴ پروژه پایدار · ۱ نیازمند توجه</small></div></section>
  {created&&<div className="projects-created"><CheckCircle2/><div><b>Draft پروژه جدید ایجاد شد</b><span>State واقعی بازخورد ایجاد آیتم.</span></div><button onClick={()=>setCreated(false)}>بستن</button></div>}
  <section className="projects-metrics"><article><span>پروژه فعال</span><strong>۵</strong><small>۲ تحویل این ماه</small></article><article><span>بودجه در گردش</span><strong>۱٫۸۳ <small>میلیارد</small></strong><small>۷۶٪ تخصیص‌یافته</small></article><article><span>Task باز</span><strong>۴۸</strong><small>۱۲ مورد اولویت‌دار</small></article><article className="risk"><span>ریسک بالا</span><strong>۱</strong><small>Dorsa Intelligence</small></article></section>
  <section className="projects-panel"><div className="projects-toolbar"><div className="projects-search"><Search/><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="جستجوی پروژه یا مشتری..." aria-label="جستجوی پروژه"/></div><div className="projects-filters">{["همه","در حال اجرا","بازبینی","ریسک","تکمیل‌شده"].map((item)=><button key={item} className={filter===item?"active":""} onClick={()=>setFilter(item)}>{item}</button>)}</div></div><div className="project-card-grid">{visible.map((project)=><article key={project.id} className="project-card"><div className="project-card-head"><span className={`project-status ${project.status==="ریسک"?"danger":project.status==="تکمیل‌شده"?"success":project.status==="بازبینی"?"review":"active"}`}>{project.status}</span><DropdownMenu><DropdownMenuTrigger asChild><button className="project-menu" aria-label={`عملیات ${project.name}`}><MoreHorizontal/></button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem>بازکردن پروژه</DropdownMenuItem><DropdownMenuItem>ویرایش</DropdownMenuItem><DropdownMenuItem>بایگانی</DropdownMenuItem></DropdownMenuContent></DropdownMenu></div><h2>{project.name}</h2><p>{project.client}</p><div className="project-health"><div><span>Health</span><b>{project.health}</b></div><span><i style={{width:`${project.health}%`}}/></span></div><div className="project-progress"><div><span>پیشرفت</span><b>{project.progress.toLocaleString("fa-IR")}٪</b></div><span><i style={{width:`${project.progress}%`}}/></span></div><div className="project-meta"><div><CalendarDays/><span>{project.deadline}</span></div><div><span>{project.budget}</span></div></div><div className="project-card-foot"><div className="project-avatars">{project.members.map((member,index)=><span key={`${member}-${index}`}>{member}</span>)}</div><button>جزئیات <ArrowUpRight/></button></div></article>)}</div>{visible.length===0&&<div className="projects-empty"><FolderKanban/><h2>پروژه‌ای پیدا نشد</h2><p>فیلتر یا عبارت جستجو را تغییر بده.</p></div>}</section>
  <section className="projects-board"><div className="projects-board-head"><div><h2>Board عملیاتی</h2><p>نمای سریع Taskهای این Sprint</p></div><span>۱۱ Task</span></div><div className="board-columns"><Board title="برای انجام" tone="todo" items={tasks.todo}/><Board title="در حال انجام" tone="doing" items={tasks.doing}/><Board title="بازبینی" tone="review" items={tasks.review}/><Board title="انجام‌شده" tone="done" items={tasks.done}/></div></section>
 </main></LoraniqShell>
}
function Board({title,tone,items}:{title:string;tone:string;items:string[]}){return <div className="board-column"><div className="board-title"><span className={tone}/><b>{title}</b><em>{items.length.toLocaleString("fa-IR")}</em></div>{items.map((item,index)=><article key={item}><div><span className={`task-priority ${index===0?"high":"normal"}`}>{index===0?"اولویت بالا":"عادی"}</span>{tone==="doing"&&<UsersRound/>}{tone==="review"&&<CircleAlert/>}{tone==="done"&&<CheckCircle2/>}</div><h3>{item}</h3><small>#{(241+index).toLocaleString("fa-IR")}</small></article>)}</div>}
