import Image from "next/image";
import Link from "next/link";
import { ArrowLeft, Blocks, Check, Code2, Command, Gauge, Languages, Layers3, LayoutDashboard, MoonStar, MousePointer2, PanelsTopLeft, ShieldCheck, Sparkles, SwatchBook, Table2, WandSparkles } from "lucide-react";
import { MarketingShell } from "@/components/marketing-shell";

const basePath=process.env.NEXT_PUBLIC_BASE_PATH??"";
const demos=[
 {slug:"executive",title:"Executive",fa:"مدیریتی",href:"/",desc:"تصمیم‌گیری مدیریتی، KPI، درآمد و سلامت کسب‌وکار."},
 {slug:"analytics",title:"Analytics",fa:"تحلیل داده",href:"/analytics/",desc:"رفتار کاربر، acquisition، funnel و پراکندگی جغرافیایی."},
 {slug:"ecommerce",title:"Ecommerce",fa:"فروشگاه",href:"/ecommerce/",desc:"فروش، سفارش، کانال، موجودی و عملیات fulfilment."},
 {slug:"crm",title:"CRM",fa:"مشتری",href:"/crm/",desc:"سلامت مشتری، retention، CLV، segment و ریسک ریزش."},
 {slug:"finance",title:"Finance",fa:"مالی",href:"/finance/",desc:"جریان نقدی، سود، بودجه و شاخص‌های مالی."},
 {slug:"healthcare",title:"Healthcare",fa:"سلامت",href:"/healthcare/",desc:"مراجعه، ظرفیت، زمان انتظار و جریان عملیات درمانی."},
];
const features=[
 {icon:Languages,title:"RTL / LTR واقعی",text:"تغییر جهت در runtime با logical CSS و محتوای فارسی/انگلیسی."},
 {icon:MoonStar,title:"Light / Dark",text:"توکن‌های مستقل برای هر پوسته؛ نه inversion یا patch سطحی."},
 {icon:SwatchBook,title:"Customizer",text:"تراکم، Skin، عرض محتوا، Sidebar و Motion با persistence."},
 {icon:Blocks,title:"Component Lab",text:"کامپوننت‌ها، feedback و Data/Empty/Error states قابل مشاهده."},
 {icon:Command,title:"Command Palette",text:"جستجوی سریع صفحه‌ها با Ctrl/⌘ + K و keyboard flow."},
 {icon:Table2,title:"Data & Forms",text:"جدول responsive، bulk selection، فیلتر، فرم و wizard واقعی."},
 {icon:Gauge,title:"Responsive QA",text:"Desktop، Tablet و Mobile در Chromium و بدون overflow افقی."},
 {icon:ShieldCheck,title:"Asset discipline",text:"فونت self-hosted و دارایی‌های مستقل با provenance ثبت‌شده."},
];
export default function LandingPage(){return <MarketingShell><main id="main-content" className="landing-page">
 <section className="landing-hero"><div className="landing-hero-copy"><span className="landing-kicker"><Sparkles/> Persian-first admin system</span><h1>پنل مدیریتی مدرن؛<br/><em>برای محصول واقعی، نه فقط ویترین.</em></h1><p>لورانیک ادمین یک قالب RTL-first با داشبوردهای مستقل، اپلیکیشن‌های عملیاتی، تنظیمات سراسری، Dark/Light و معماری React/Next مدرن است.</p><div className="landing-hero-actions"><Link className="marketing-cta" href="/demos/">مشاهده دموها <ArrowLeft/></Link><Link className="marketing-ghost" href="/components/"><Blocks/> Component Lab</Link></div><div className="landing-proof"><span><Check/> ۶ داشبورد شاخص مستقل</span><span><Check/> ۲۰+ مسیر اپلیکیشن و ابزار</span><span><Check/> RTL/LTR + Dark/Light</span></div></div><div className="landing-stage" aria-label="پیش‌نمایش واقعی داشبوردها"><div className="stage-glow"/><div className="stage-window main"><div className="stage-browser"><i/><i/><i/><span>loraniq / executive</span></div><Image src={`${basePath}/demo-previews/executive.jpg`} width={960} height={600} priority alt="پیش‌نمایش واقعی داشبورد Executive لورانیک"/></div><div className="stage-window float-one"><Image src={`${basePath}/demo-previews/ecommerce.jpg`} width={960} height={600} alt="پیش‌نمایش واقعی داشبورد Ecommerce"/></div><div className="stage-window float-two"><Image src={`${basePath}/demo-previews/analytics.jpg`} width={960} height={600} alt="پیش‌نمایش واقعی داشبورد Analytics"/></div><span className="stage-chip chip-one"><MousePointer2/> Interactive</span><span className="stage-chip chip-two"><WandSparkles/> RTL native</span></div></section>
 <section className="landing-strip"><span>React 19</span><i/> <span>Next.js 16</span><i/> <span>TypeScript 5</span><i/> <span>Tailwind CSS 4</span><i/> <span>Radix / Base UI</span><i/> <span>Lucide</span></section>
 <section id="features" className="landing-section"><div className="section-heading"><span>Design system</span><h2>Polish فقط ظاهر نیست؛ رفتار هم بخشی از طراحی است.</h2><p>هدف، همان آرامش بصری قالب‌های premium همراه با ساختار قابل توسعه و stateهای واقعی است.</p></div><div className="feature-grid">{features.map(({icon:Icon,title,text})=><article key={title}><span><Icon/></span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
 <section className="landing-demos"><div className="section-heading inline"><div><span>Flagship demos</span><h2>شش مسئله، شش ترکیب مستقل.</h2></div><Link href="/demos/">همه دموها <ArrowLeft/></Link></div><div className="landing-demo-grid">{demos.map((demo,index)=><Link href={demo.href} className="landing-demo-card" key={demo.slug}><div className="demo-shot"><Image src={`${basePath}/demo-previews/${demo.slug}.jpg`} width={960} height={600} alt={`پیش‌نمایش واقعی ${demo.title}`}/><span>0{index+1}</span></div><div><p>{demo.fa}</p><h3>{demo.title}</h3><small>{demo.desc}</small><em>بازکردن دمو <ArrowLeft/></em></div></Link>)}</div></section>
 <section id="architecture" className="landing-architecture"><div className="architecture-copy"><span className="landing-kicker"><Code2/> Developer experience</span><h2>ساختار قابل فهم برای توسعه‌دهنده بعدی.</h2><p>Shell مشترک، primitives قابل‌استفاده مجدد، semantic tokens، routeهای مستقل و UI preferences سراسری؛ بدون وابستگی ضروری به CDN یا asset پولی.</p><ul><li><Check/> کامپوننت‌های پایه Radix/Base UI و shadcn-style</li><li><Check/> فونت فارسی Vazirmatn به‌صورت self-hosted</li><li><Check/> CSS logical برای RTL/LTR</li><li><Check/> reduced-motion و focus-visible</li></ul><Link className="marketing-ghost" href="/settings/"><SwatchBook/> بازکردن Customizer</Link></div><div className="architecture-stack"><article><span><Layers3/></span><b>Application shell</b><small>Navigation · topbar · command palette</small></article><article><span><PanelsTopLeft/></span><b>Feature routes</b><small>Dashboards · Apps · Auth · Utility</small></article><article><span><Blocks/></span><b>UI primitives</b><small>Stateful · reusable · accessible-first</small></article><article><span><LayoutDashboard/></span><b>Theme system</b><small>Tokens · density · skins · motion</small></article></div></section>
 <section className="landing-cta"><div><span><Sparkles/> Explore Loraniq</span><h2>از یک داشبورد شروع کن؛ کل سیستم را ببین.</h2><p>دموها به همان صفحات واقعی محصول وصل‌اند؛ تصویر تزئینی جدا از محصول نیست.</p></div><div><Link className="marketing-cta" href="/demos/">انتخاب دمو <ArrowLeft/></Link><Link className="marketing-ghost invert" href="/login/">مشاهده Auth</Link></div></section>
 </main></MarketingShell>}
