import "../marketing-premium.css";
import Image from "next/image";
import Link from "next/link";
import { ArrowLeft, Blocks, CalendarDays, Check, Code2, Command, FileText, Gauge, Languages, Layers3, LayoutDashboard, Mail, MessageSquare, MoonStar, MousePointer2, PanelsTopLeft, Settings, ShieldCheck, ShoppingCart, Sparkles, SwatchBook, Table2, Users, WandSparkles } from "lucide-react";
import { MarketingShell } from "@/components/marketing-shell";

const basePath=process.env.NEXT_PUBLIC_BASE_PATH??"";
const demos=[
 {slug:"executive",title:"Executive",fa:"مدیریتی",href:"/",desc:"تصمیم‌گیری مدیریتی، KPI، درآمد و سلامت کسب‌وکار."},
 {slug:"analytics",title:"Analytics",fa:"تحلیل داده",href:"/analytics/",desc:"رفتار کاربر، acquisition، funnel و پراکندگی جغرافیایی."},
 {slug:"ecommerce",title:"Ecommerce",fa:"فروشگاه",href:"/ecommerce/",desc:"فروش، سفارش، کانال، موجودی و عملیات fulfilment."},
 {slug:"crm",title:"CRM",fa:"مشتری",href:"/crm/",desc:"سلامت مشتری، retention، CLV، segment و ریسک ریزش."},
 {slug:"finance",title:"Finance",fa:"مالی",href:"/finance/",desc:"جریان نقدی، سود، بودجه و شاخص‌های مالی."},
 {slug:"healthcare",title:"Healthcare",fa:"سلامت",href:"/healthcare/",desc:"مراجعه، ظرفیت، زمان انتظار و جریان عملیات درمانی."},
];
const stats=[{value:"+۲۰",label:"مسیر و صفحه کاربردی"},{value:"RTL / LTR",label:"فارسی و انگلیسی"},{value:"۶",label:"داشبورد آماده"},{value:"Dark / Light",label:"دو پوسته کامل"}];
const technologies=[
 {name:"Next.js 16",mark:"N",tone:"next"},
 {name:"React 19",mark:"⚛",tone:"react"},
 {name:"TypeScript",mark:"TS",tone:"typescript"},
 {name:"Tailwind 4",mark:"TW",tone:"tailwind"},
 {name:"Radix UI",mark:"R",tone:"radix"},
 {name:"Lucide",mark:"✦",tone:"lucide"},
 {name:"Vazirmatn",mark:"آ",tone:"font"},
 {name:"RTL / LTR",mark:"↔",tone:"rtl"},
];
const features=[
 {icon:SwatchBook,title:"طراحی مدرن و مینیمال",text:"سطح‌های تمیز، فاصله‌گذاری آرام، کارت‌های سبک و رنگ‌بندی نزدیک به قالب‌های premium."},
 {icon:Layers3,title:"صفحات متعدد",text:"داشبورد، اپلیکیشن، جدول، فرم، فایل، تقویم، احراز هویت و صفحات خطا در یک بسته."},
 {icon:Blocks,title:"اپلیکیشن‌های آماده",text:"ایمیل، چت، Kanban، فایل، پروژه، کاربران، تقویم و مسیرهای عملیاتی واقعی."},
 {icon:MoonStar,title:"حالت روز و شب",text:"Dark و Light بر پایه توکن‌های مستقل، نه فقط معکوس‌سازی رنگ‌ها."},
 {icon:Settings,title:"شخصی‌سازی آسان",text:"تغییر جهت، پوسته، تراکم، motion و تنظیمات ظاهری از UI سراسری."},
 {icon:Languages,title:"چندزبانه و دو جهته",text:"RTL/LTR در runtime با CSS logical و محتوای فارسی/انگلیسی قابل توسعه."},
 {icon:Code2,title:"کدنویسی تمیز",text:"ساختار Next، کامپوننت‌های جدا، routeهای مشخص و دارایی‌های self-hosted."},
 {icon:ShieldCheck,title:"آماده‌سازی فروش",text:"بدون وابستگی ضروری به CDN یا asset پولی و مناسب بسته‌بندی محصول مستقل."},
 {icon:Gauge,title:"ریسپانسیو واقعی",text:"چیدمان‌ها برای دسکتاپ، تبلت و موبایل دوباره سازمان‌دهی می‌شوند."},
 {icon:Command,title:"جستجو و فرمان سریع",text:"Command Palette برای حرکت سریع بین صفحات و تجربه نزدیک‌تر به پنل حرفه‌ای."},
 {icon:Table2,title:"داده و فرم",text:"جدول، فیلتر، انتخاب گروهی، فرم، validation و stateهای خالی/خطا."},
 {icon:WandSparkles,title:"موشن کنترل‌شده",text:"تعامل‌های hover و focus نرم، همراه با پشتیبانی reduced motion."},
];
const apps=[
 {icon:Mail,title:"ایمیل",href:"/email/",shot:"analytics"},
 {icon:MessageSquare,title:"پیام‌رسان",href:"/chat/",shot:"crm"},
 {icon:CalendarDays,title:"تقویم",href:"/calendar/",shot:"finance"},
 {icon:ShoppingCart,title:"فروشگاه",href:"/ecommerce/",shot:"ecommerce"},
 {icon:Users,title:"کاربران",href:"/users/",shot:"healthcare"},
 {icon:FileText,title:"فایل‌ها",href:"/files/",shot:"executive"},
];
const pages=[{title:"ورود",href:"/login/"},{title:"ثبت‌نام",href:"/register/"},{title:"فراموشی رمز",href:"/forgot-password/"},{title:"تایید ایمیل",href:"/verify-email/"},{title:"احراز دومرحله‌ای",href:"/two-factor/"},{title:"قفل صفحه",href:"/lock-screen/"}];
const puzzle=["آکاردئون","هشدارها","برچسب‌ها","دکمه‌ها","اسلایدر","پاپ‌آپ منو","مدال‌ها","کشوی کناری","صفحه‌بندی","نوار پیشرفت","اسپینر","تب‌ها","توست مسیج","تولتیپ","آواتار","جدول داده","فرم‌ها","انتخابگر","نمودارها","تقویم","جستجو","تنظیمات","Breadcrumb","کارت‌ها","Wizard","Navigation","Dropdown","Checkbox","Radio","Switch","Textarea","Empty State","Error State","Loading","RTL/LTR","Dark Mode"];

export default function LandingPage(){return <MarketingShell landing><main id="main-content" className="landing-page">
 <section id="top" className="landing-hero"><div className="landing-hero-copy"><span className="landing-kicker"><Sparkles/> قالب مدیریت فارسی و مدرن</span><h1>پنل مدیریت مناسب برای هر سایت و اپلیکیشن <em>Loraniq Admin</em></h1><p>لورانیک ادمین یک قالب مدیریتی آماده استفاده برای پروژه‌های فارسی و بین‌المللی است؛ همراه با داشبوردهای واقعی، اپلیکیشن‌های کاربردی، حالت روشن و تاریک، RTL/LTR و ساختار توسعه‌پذیر.</p><div className="landing-hero-actions"><Link className="marketing-cta" href="/demos/">مشاهده دموها <ArrowLeft/></Link><Link className="marketing-ghost" href="/components/"><Blocks/> کامپوننت‌ها</Link></div><div className="landing-proof">{stats.map((item)=><span key={item.label}><b>{item.value}</b><small>{item.label}</small></span>)}</div></div><div className="landing-stage" aria-label="پیش‌نمایش واقعی داشبوردها"><div className="stage-glow"/><div className="stage-window main"><div className="stage-browser"><i/><i/><i/><span>loraniq / executive</span></div><Image src={`${basePath}/demo-previews/executive.jpg`} width={960} height={600} priority fetchPriority="high" alt="پیش‌نمایش واقعی داشبورد Executive لورانیک"/></div><div className="stage-window float-one"><Image src={`${basePath}/demo-previews/ecommerce.jpg`} width={960} height={600} loading="lazy" fetchPriority="low" alt="پیش‌نمایش واقعی داشبورد Ecommerce"/></div><div className="stage-window float-two"><Image src={`${basePath}/demo-previews/analytics.jpg`} width={960} height={600} loading="lazy" fetchPriority="low" alt="پیش‌نمایش واقعی داشبورد Analytics"/></div><span className="stage-chip chip-one"><MousePointer2/> Interactive</span><span className="stage-chip chip-two"><WandSparkles/> RTL native</span></div></section>
 <section className="landing-strip" aria-label="تکنولوژی‌های پروژه">{technologies.map((item)=><span className={`tech-pill ${item.tone}`} key={item.name}><b>{item.mark}</b><small>{item.name}</small></span>)}</section>
 <section id="demos" className="landing-demos" aria-label="دموهای آماده"><div className="section-heading"><span>Ready demos</span><h2>دموهای آماده برای سلیقه‌های متفاوت</h2><p>چند ترکیب آماده از داشبوردهای لورانیک برای نمایش سریع قدرت محصول و شروع توسعه.</p></div><div className="landing-demo-grid">{demos.map((demo,index)=><Link href={demo.href} className="landing-demo-card" key={demo.slug}><div className="demo-shot"><div className="demo-shot-head"><strong>{demo.fa}</strong><span className="demo-direction"><b>LTR</b><b>RTL</b></span></div><Image src={`${basePath}/demo-previews/${demo.slug}.jpg`} width={960} height={600} loading="lazy" fetchPriority="low" alt={`پیش‌نمایش واقعی ${demo.title}`}/><span>0{index+1}</span></div><div><p>{demo.fa}</p><h3>{demo.title}</h3><small>{demo.desc}</small><em>مشاهده <ArrowLeft/></em></div></Link>)}</div></section>
 <section className="landing-vuexy-band"><div className="band-shot"><Image src={`${basePath}/demo-previews/crm.jpg`} width={960} height={600} loading="lazy" fetchPriority="low" alt="نمای تاریک داشبورد لورانیک"/></div><div><span>All-in-one admin</span><h2>لورانیک، یک پنل مدیریت تمام‌عیار</h2><p>هدف لورانیک فقط ساخت چند کارت زیبا نیست؛ یک سیستم آماده برای پنل‌های واقعی است: مسیرهای کاربردی، stateهای کامل، تنظیمات UI و ساختار قابل توسعه.</p><Link className="marketing-cta" href="/demos/">شروع کنید <ArrowLeft/></Link></div></section>
 <section id="features" className="landing-section"><div className="section-heading"><span>Key features</span><h2>ویژگی‌های شاخص</h2><p>امکاناتی که برای فروش حرفه‌ای قالب مدیریت مهم‌اند: ظاهر قابل اعتماد، رفتار واقعی و آماده‌بودن برای توسعه.</p></div><div className="feature-grid">{features.map(({icon:Icon,title,text})=><article key={title}><span><Icon/></span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
  <section id="apps" className="landing-showcase apps-showcase" aria-label="اپلیکیشن‌های آماده"><div className="section-heading"><span>Ready apps</span><h2>اپلیکیشن‌های آماده و کاربردی</h2><p>چند مسیر عملیاتی آماده که باعث می‌شود محصول فقط یک داشبورد تزئینی نباشد.</p></div><div className="landing-showcase-grid app-card-grid">{apps.map(({icon:Icon,title,href,shot})=><Link className="mini-preview-card" href={href} key={title}><div className="mini-preview-head"><span><Icon/></span><h3>{title}</h3><b>LTR / RTL</b></div><Image src={`${basePath}/demo-previews/${shot}.jpg`} width={960} height={600} loading="lazy" fetchPriority="low" alt={`پیش‌نمایش ${title}`}/><em>مشاهده <ArrowLeft/></em></Link>)}</div></section>
 <section className="landing-auth-band"><div><span>Auth & utility</span><h2>صفحات احراز هویت و ابزارهای آماده</h2><p>صفحات ورود، ثبت‌نام، تایید ایمیل، قفل صفحه، خطا و مسیرهای کمکی برای کامل‌تر شدن بسته محصول.</p><Link className="marketing-cta" href="/login/">مشاهده Auth <ArrowLeft/></Link></div><div className="auth-illustration"><Image src={`${basePath}/illustrations/apps-system.svg`} width={720} height={480} loading="lazy" fetchPriority="low" alt="نمای اپلیکیشن‌ها و صفحات آماده لورانیک"/></div></section>
  <section id="pages" className="landing-demos landing-pages-section"><div className="section-heading"><span>Extra pages</span><h2>صفحات متنوع و متعدد</h2><p>نمونه‌ای از صفحات عمومی و احراز هویت که برای یک قالب مدیریت کامل لازم‌اند.</p></div><div className="simple-page-grid">{pages.map((page)=><Link href={page.href} key={page.title}><Image src={`${basePath}/demo-previews/analytics.jpg`} width={960} height={600} loading="lazy" fetchPriority="low" alt={`پیش‌نمایش صفحه ${page.title}`}/><span>{page.title}</span><small>RTL / LTR</small></Link>)}</div></section>
  <section id="cards" className="landing-cards-section"><div className="section-heading"><span>Advanced cards</span><h2>کارت‌های پیشرفته برای ساخت داشبورد</h2><p>با ترکیب کارت‌های آمار، نمودار، جدول و پروفایل می‌شود صفحات مدیریتی کامل و قابل فروش ساخت.</p></div><div className="cards-collage"><Image src={`${basePath}/demo-previews/ecommerce.jpg`} width={960} height={600} loading="lazy" fetchPriority="low" alt="کارت‌ها و ویجت‌های فروشگاهی لورانیک"/><Image src={`${basePath}/demo-previews/finance.jpg`} width={960} height={600} loading="lazy" fetchPriority="low" alt="کارت‌ها و ویجت‌های مالی لورانیک"/><Image src={`${basePath}/demo-previews/healthcare.jpg`} width={960} height={600} loading="lazy" fetchPriority="low" alt="کارت‌ها و ویجت‌های سلامت لورانیک"/></div></section>
  <section id="components" className="landing-puzzle-section"><div className="section-heading"><span>UI puzzle</span><h2>اجزای پازل پنل مدیریت شما</h2><p>کامپوننت‌ها و الگوهای آماده برای ساخت سریع‌تر صفحه‌های مدیریتی.</p></div><div className="puzzle-grid">{puzzle.map((item)=><Link href="/components/" key={item}><Blocks/><span>{item}</span></Link>)}</div></section>
 <section id="architecture" className="landing-architecture"><div className="architecture-copy"><span className="landing-kicker"><Code2/> Developer experience</span><h2>ساختار قابل فهم برای توسعه‌دهنده بعدی.</h2><p>Shell مشترک، primitives قابل‌استفاده مجدد، semantic tokens، routeهای مستقل و UI preferences سراسری؛ بدون وابستگی ضروری به CDN یا asset پولی.</p><ul><li><Check/> کامپوننت‌های پایه Radix/Base UI و shadcn-style</li><li><Check/> فونت فارسی Vazirmatn به‌صورت self-hosted</li><li><Check/> CSS logical برای RTL/LTR</li><li><Check/> reduced-motion و focus-visible</li></ul><Link className="marketing-ghost" href="/settings/"><SwatchBook/> بازکردن Customizer</Link></div><div className="architecture-stack"><article><span><Layers3/></span><b>Application shell</b><small>Navigation · topbar · command palette</small></article><article><span><PanelsTopLeft/></span><b>Feature routes</b><small>Dashboards · Apps · Auth · Utility</small></article><article><span><Blocks/></span><b>UI primitives</b><small>Stateful · reusable · accessible-first</small></article><article><span><LayoutDashboard/></span><b>Theme system</b><small>Tokens · density · skins · motion</small></article></div></section>
  <section id="faq" className="landing-faq"><div className="faq-copy"><span>FAQ</span><h2>سوالات متداول</h2><p>چند نکته مهم برای خریدار و توسعه‌دهنده محصول.</p></div><div><article className="landing-faq-item"><h3>آیا لورانیک فقط یک صفحه فروش است؟</h3><p>خیر؛ دموها به مسیرهای واقعی محصول وصل‌اند و صفحه فروش فقط آن‌ها را معرفی می‌کند.</p></article><article className="landing-faq-item"><h3>آیا دارایی خارجی اجباری دارد؟</h3><p>فونت و assetهای اصلی داخل پروژه قرار دارند و برای اجرای ظاهر اصلی به CDN پولی وابسته نیست.</p></article><article className="landing-faq-item"><h3>آیا RTL و LTR واقعی است؟</h3><p>تغییر جهت در runtime انجام می‌شود و استایل‌ها با رویکرد logical نوشته شده‌اند.</p></article></div></section>
 <section className="landing-cta"><div><span><Sparkles/> Explore Loraniq</span><h2>از یک داشبورد شروع کن؛ کل سیستم را ببین.</h2><p>دموها به همان صفحات واقعی محصول وصل‌اند؛ تصویر تزئینی جدا از محصول نیست.</p></div><div><Link className="marketing-cta" href="/demos/">انتخاب دمو <ArrowLeft/></Link><Link className="marketing-ghost invert" href="/login/">مشاهده Auth</Link></div></section>
 </main><a className="landing-backtop" href="#top" aria-label="بازگشت به ابتدای صفحه">↑</a></MarketingShell>}
