"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Bell, CalendarDays, CheckCircle2, ChevronLeft, ChevronRight, CircleDollarSign, Command, CreditCard, FileText, GraduationCap, Grid2X2, HelpCircle, Home, Inbox, Layers3, LayoutDashboard, Menu, MessageCircle, Moon, Package, Plus, Search, Settings, ShoppingBag, Sun, TrendingUp, Users, WalletCards, X } from "lucide-react";
import "./dashboard.css";

const modules = [
  {slug:"commerce",label:"تجارت",icon:ShoppingBag},{slug:"analytics",label:"تحلیل داده",icon:TrendingUp},
  {slug:"projects",label:"پروژه‌ها",icon:Layers3},{slug:"finance",label:"امور مالی",icon:WalletCards},
  {slug:"crm",label:"مشتریان",icon:Users},{slug:"academy",label:"آکادمی",icon:GraduationCap},
  {slug:"calendar",label:"تقویم",icon:CalendarDays},{slug:"inbox",label:"پیام‌ها",icon:Inbox},
  {slug:"components",label:"کامپوننت‌ها",icon:Grid2X2},{slug:"settings",label:"تنظیمات",icon:Settings},
];
const meta:Record<string,{title:string,sub:string}>={commerce:{title:"داشبورد تجارت",sub:"عملکرد فروشگاه و سفارش‌های امروز"},analytics:{title:"تحلیل داده",sub:"نمای جامع شاخص‌های رشد کسب‌وکار"},projects:{title:"مدیریت پروژه‌ها",sub:"پیشرفت تیم و تحویل‌های نزدیک"},finance:{title:"امور مالی",sub:"جریان نقدی، درآمد و هزینه‌ها"},crm:{title:"مدیریت مشتریان",sub:"سرنخ‌ها، ارتباطات و فروش"},academy:{title:"آکادمی آنلاین",sub:"دوره‌ها، مدرس‌ها و دانشجویان"},calendar:{title:"تقویم و برنامه‌ریزی",sub:"رویدادها و جلسه‌های تیم"},inbox:{title:"صندوق پیام",sub:"مکالمه‌ها و درخواست‌های مشتریان"},components:{title:"کتابخانه کامپوننت‌ها",sub:"المان‌های رابط کاربری لورانیک"},settings:{title:"تنظیمات حساب",sub:"پروفایل، امنیت و ترجیحات پنل"}};
const trend=[{n:"شنبه",v:24,p:18},{n:"یکشنبه",v:31,p:23},{n:"دوشنبه",v:27,p:21},{n:"سه‌شنبه",v:45,p:29},{n:"چهارشنبه",v:39,p:33},{n:"پنجشنبه",v:57,p:38},{n:"جمعه",v:64,p:45}];
const orders=[{id:"#LR-8421",name:"آرمان رضایی",item:"هدفون بی‌سیم",date:"۱۸ شهریور، ۱۰:۳۵",price:"۳٬۸۴۰٬۰۰۰",status:"پرداخت‌شده"},{id:"#LR-8420",name:"سارا احمدی",item:"ساعت هوشمند",date:"۱۸ شهریور، ۰۹:۲۱",price:"۵٬۲۱۰٬۰۰۰",status:"در انتظار"},{id:"#LR-8419",name:"مهدی کریمی",item:"کیبورد مکانیکی",date:"۱۷ شهریور، ۲۲:۴۰",price:"۲٬۹۸۰٬۰۰۰",status:"ارسال‌شده"},{id:"#LR-8418",name:"نیلوفر صالحی",item:"ماوس ارگونومیک",date:"۱۷ شهریور، ۲۰:۱۲",price:"۱٬۴۵۰٬۰۰۰",status:"پرداخت‌شده"}];

function Stat({icon:Icon,label,value,delta,tone}:{icon:any,label:string,value:string,delta:string,tone:string}){return <article className="a-stat"><span className={tone}><Icon/></span><div><small>{label}</small><strong>{value}</strong><em><TrendingUp/> {delta} نسبت به ماه قبل</em></div></article>}
function Commerce(){return <><div className="a-stats"><Stat icon={CircleDollarSign} label="درآمد کل" value="۸۴۲٫۶ مـ" delta="۱۲٫۵٪" tone="purple"/><Stat icon={ShoppingBag} label="سفارش‌ها" value="۲٬۸۴۰" delta="۸٫۲٪" tone="blue"/><Stat icon={Users} label="مشتریان جدید" value="۱٬۲۴۸" delta="۶٫۸٪" tone="green"/><Stat icon={Package} label="میانگین سبد" value="۲٫۹۶ مـ" delta="۴٫۱٪" tone="orange"/></div><div className="a-grid"><section className="a-card chart-wide"><header><div><h3>روند درآمد</h3><p>مقایسه فروش و هزینه در هفته اخیر</p></div><select><option>۷ روز اخیر</option><option>۳۰ روز اخیر</option></select></header><ResponsiveContainer width="100%" height={280}><AreaChart data={trend}><defs><linearGradient id="pv" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#7367f0" stopOpacity=".35"/><stop offset="1" stopColor="#7367f0" stopOpacity="0"/></linearGradient></defs><CartesianGrid vertical={false} stroke="var(--a-line)"/><XAxis dataKey="n" axisLine={false} tickLine={false}/><YAxis hide/><Tooltip/><Area type="monotone" dataKey="v" stroke="#7367f0" strokeWidth={3} fill="url(#pv)"/><Area type="monotone" dataKey="p" stroke="#42c7a5" strokeWidth={2} fill="transparent" strokeDasharray="6 5"/></AreaChart></ResponsiveContainer></section><section className="a-card donut"><header><div><h3>منابع فروش</h3><p>سهم کانال‌ها</p></div><button>•••</button></header><ResponsiveContainer width="100%" height={185}><PieChart><Pie data={[{v:48},{v:27},{v:16},{v:9}]} dataKey="v" innerRadius={58} outerRadius={78} paddingAngle={4}>{["#7367f0","#45c7a6","#ff9f67","#5b93e8"].map(c=><Cell key={c} fill={c}/>)}</Pie></PieChart></ResponsiveContainer><div className="donut-center"><b>۴۸٪</b><small>فروشگاه</small></div><div className="legend"><span><i/>فروشگاه ۴۸٪</span><span><i/>شبکه اجتماعی ۲۷٪</span><span><i/>مارکت‌پلیس ۱۶٪</span><span><i/>سایر ۹٪</span></div></section></div><Orders/></>}
function Orders(){return <section className="a-card orders"><header><div><h3>سفارش‌های اخیر</h3><p>آخرین تراکنش‌های ثبت‌شده در فروشگاه</p></div><button className="soft-btn">مشاهده همه <ChevronLeft/></button></header><div className="table-wrap"><table><thead><tr><th>سفارش</th><th>مشتری</th><th>محصول</th><th>تاریخ</th><th>مبلغ (تومان)</th><th>وضعیت</th></tr></thead><tbody>{orders.map((o,i)=><tr key={o.id}><td><b>{o.id}</b></td><td><span className={`customer c${i}`}>{o.name[0]}</span>{o.name}</td><td>{o.item}</td><td>{o.date}</td><td><b>{o.price}</b></td><td><em className={`status s${i}`}>{o.status}</em></td></tr>)}</tbody></table></div></section>}
function Analytics(){return <><div className="a-stats"><Stat icon={Users} label="کاربران فعال" value="۱۸٬۲۹۴" delta="۹٫۶٪" tone="purple"/><Stat icon={TrendingUp} label="نرخ تبدیل" value="۷٫۸٪" delta="۱٫۴٪" tone="green"/><Stat icon={FileText} label="بازدید صفحات" value="۹۶٫۲K" delta="۱۴٫۳٪" tone="blue"/><Stat icon={CreditCard} label="ارزش هر کاربر" value="۶۴۰ هـ" delta="۳٫۹٪" tone="orange"/></div><div className="a-grid"><section className="a-card chart-wide"><header><div><h3>رفتار کاربران</h3><p>بازدید و تبدیل روزانه</p></div></header><ResponsiveContainer width="100%" height={300}><BarChart data={trend}><CartesianGrid vertical={false} stroke="var(--a-line)"/><XAxis dataKey="n" axisLine={false} tickLine={false}/><YAxis hide/><Tooltip/><Bar dataKey="v" fill="#7367f0" radius={[6,6,0,0]}/><Bar dataKey="p" fill="#dcd8ff" radius={[6,6,0,0]}/></BarChart></ResponsiveContainer></section><section className="a-card realtime"><header><h3>فعالیت زنده</h3></header><strong>۱٬۲۸۴</strong><p>کاربر اکنون آنلاین است</p><div className="pulse-map">{Array.from({length:22}).map((_,i)=><i key={i}/>)}</div><span className="live"><i/> بروزرسانی زنده</span></section></div><Orders/></>}
function Projects(){const cards=[{t:"بازطراحی اپلیکیشن",p:78,tag:"طراحی محصول",color:"purple"},{t:"کمپین پاییز",p:54,tag:"بازاریابی",color:"orange"},{t:"داشبورد مدیران",p:92,tag:"توسعه",color:"green"}];return <div className="project-board">{["برنامه‌ریزی","در حال انجام","بازبینی"].map((col,ci)=><section key={col}><header><b>{col}</b><span>{ci+2}</span><Plus/></header>{cards.slice(ci?ci-1:0,ci?3:2).map((c,i)=><article className="task" key={c.t}><span className={c.color}>{c.tag}</span><h3>{c.t}</h3><p>همگام‌سازی تجربه کاربری با سیستم طراحی جدید لورانیک.</p><div className="progress"><i style={{width:`${c.p}%`}}/></div><small>{c.p}٪ تکمیل شده</small><footer><div className="mini-faces"><i>ن</i><i>ع</i><i>م</i></div><span><MessageCircle/> {i+3}</span></footer></article>)}</section>)}</div>}
function CalendarView(){return <section className="a-card calendar-view"><header><div><h3>شهریور ۱۴۰۵</h3><p>۴ رویداد برای امروز</p></div><div><button><ChevronRight/></button><button>امروز</button><button><ChevronLeft/></button></div></header><div className="week">{["شنبه","یکشنبه","دوشنبه","سه‌شنبه","چهارشنبه","پنجشنبه","جمعه"].map(x=><b key={x}>{x}</b>)}{Array.from({length:35}).map((_,i)=><span className={i===17?"today":""} key={i}><i>{i<2?29+i:i-1}</i>{[7,10,17,23].includes(i)&&<em>{i===17?"جلسه تیم محصول":"بررسی پروژه"}</em>}</span>)}</div></section>}
function Components(){return <div className="component-grid"><section className="a-card"><header><h3>دکمه‌ها و وضعیت‌ها</h3></header><div className="component-row"><button className="primary-btn">عملیات اصلی</button><button className="soft-btn">دکمه ثانویه</button><button className="danger-btn">حذف</button><span className="status s0">موفق</span><span className="status s1">در انتظار</span></div></section><section className="a-card"><header><h3>ورودی‌ها</h3></header><div className="form-row"><label>نام کامل<input placeholder="مثلاً نگار احمدی"/></label><label>نقش کاربر<select><option>مدیر محصول</option></select></label><label className="toggle-label"><span>اعلان‌ها</span><i className="toggle"/></label></div></section><section className="a-card"><header><h3>هشدارها و پیام‌ها</h3></header><div className="alerts"><p className="success"><CheckCircle2/> تغییرات با موفقیت ذخیره شد.</p><p className="info"><HelpCircle/> نسخه محصول روی ۱.۰.۰ ثابت است.</p></div></section><Orders/></div>}
function Generic({slug}:{slug:string}){if(slug==="projects")return <Projects/>;if(slug==="calendar")return <CalendarView/>;if(slug==="components")return <Components/>;const labels:{[k:string]:string[]}={finance:["موجودی کل","درآمد ماه","هزینه‌ها","فاکتور باز"],crm:["کل مشتریان","سرنخ جدید","نرخ موفقیت","پیگیری امروز"],academy:["دانشجوی فعال","دوره منتشرشده","درآمد آموزش","رضایت کاربران"],inbox:["پیام جدید","پاسخ‌داده‌شده","زمان پاسخ","رضایت مشتری"],settings:["امنیت حساب","اعلان‌ها","اعضای تیم","فضای مصرفی"]};return <><div className="a-stats">{(labels[slug]||labels.finance).map((l,i)=><Stat key={l} icon={[WalletCards,TrendingUp,Users,FileText][i]} label={l} value={["۱۲٫۸K","۸۴٪","۲٬۴۸۰","۲۴"][i]} delta={`${12-i*2}٪`} tone={["purple","green","blue","orange"][i]}/>)}</div><div className="a-grid"><section className="a-card chart-wide"><header><div><h3>گزارش عملکرد</h3><p>روند هفت روز اخیر</p></div></header><ResponsiveContainer width="100%" height={300}><AreaChart data={trend}><CartesianGrid vertical={false} stroke="var(--a-line)"/><XAxis dataKey="n" axisLine={false} tickLine={false}/><YAxis hide/><Tooltip/><Area type="monotone" dataKey="v" stroke="#7367f0" strokeWidth={3} fill="url(#pv)"/></AreaChart></ResponsiveContainer></section><section className="a-card quick-list"><header><h3>فعالیت‌های اخیر</h3></header>{orders.map((o,i)=><div key={o.id}><span className={`customer c${i}`}>{o.name[0]}</span><p><b>{o.name}</b><small>{o.date}</small></p><CheckCircle2/></div>)}</section></div><Orders/></>}

export default function AdminDemo({slug}:{slug:string}){const [dark,setDark]=useState(false);const [mobile,setMobile]=useState(false);const [query,setQuery]=useState("");const m=meta[slug];const content=useMemo(()=>slug==="commerce"?<Commerce/>:slug==="analytics"?<Analytics/>:<Generic slug={slug}/>,[slug]);return <main dir="rtl" className={`admin ${dark?"a-dark":""}`}><aside className={`admin-side ${mobile?"show":""}`}><div className="admin-brand"><span>L</span><div><b>لورانیک</b><small>نسخه ۱.۰.۰</small></div><button onClick={()=>setMobile(false)}><X/></button></div><nav><small>فضای کاری</small><Link href="/demo/commerce" className={slug==="commerce"?"active":""}><LayoutDashboard/>پیشخوان</Link>{modules.slice(1,6).map(x=><Link href={`/demo/${x.slug}`} className={slug===x.slug?"active":""} key={x.slug}><x.icon/>{x.label}</Link>)}<small>ابزارها</small>{modules.slice(6).map(x=><Link href={`/demo/${x.slug}`} className={slug===x.slug?"active":""} key={x.slug}><x.icon/>{x.label}{x.slug==="inbox"&&<em>۶</em>}</Link>)}</nav><div className="help-card"><HelpCircle/><b>راهنمای لورانیک</b><p>مستندات و پاسخ سوال‌های شما</p><button>مشاهده راهنما</button></div><Link className="back-link" href="/"><Home/> بازگشت به لندینگ</Link></aside><section className="admin-page"><header className="admin-top"><button className="admin-menu" onClick={()=>setMobile(true)}><Menu/></button><label className="admin-search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="جستجو در لورانیک..."/><kbd><Command/> K</kbd></label><div className="top-actions"><button onClick={()=>setDark(!dark)}>{dark?<Sun/>:<Moon/>}</button><button className="bell"><Bell/><i/></button><span className="top-user"><span>نگار احمدی<small>مدیر محصول</small></span><i>ن</i></span></div></header><div className="admin-content"><div className="page-head"><div><p>لورانیک / {m.title}</p><h1>{m.title}</h1><span>{m.sub}</span></div><div><button className="soft-btn"><CalendarDays/> ۱۲ تا ۱۸ شهریور</button><button className="primary-btn"><Plus/> گزارش جدید</button></div></div>{query&&<div className="search-result">نتیجه جستجو برای «{query}» در {m.title}</div>}{content}</div></section></main>}
